version: '2'

services:
    web:
        image: nginx:1.13-alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        #image: php:7.1-fpm-alpine
        build: .
        volumes:
            - ./code:/code
        networks:
            - code-network
    postgres:
        image: postgres:9.6-alpine
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
