---
kind: Service
apiVersion: v1
metadata:
  name: php
  namespace: default
  labels:
    app: php7
spec:
  ports:
  - name: listener
    protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: php7
  type: NodePort
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  sessionAffinity: None
